package com.example.testjetpack.models.git.db

import androidx.room.*

@Entity(tableName = "repository_table", indices = [Index(value = ["index_in_response"])])
data class GitRepository(
    @ColumnInfo(name = "stargazers_count") val stargazersCount: Int,
    @ColumnInfo(name = "pushed_at") val pushedAt: String,
    @ColumnInfo(name = "subscription_url") val subscriptionUrl: String?,
    @ColumnInfo(name = "language") val language: String?,
    @ColumnInfo(name = "branches_url") val branchesUrl: String?,
    @ColumnInfo(name = "issue_comment_url") val issueCommentUrl: String?,
    @ColumnInfo(name = "labels_url") val labelsUrl: String?,
    @ColumnInfo(name = "score") val score: Double,
    @ColumnInfo(name = "subscribers_url") val subscribersUrl: String?,
    @ColumnInfo(name = "releases_url") val releasesUrl: String?,
    @ColumnInfo(name = "svn_url") val svnUrl: String,
    @ColumnInfo(name = "id") val id: Long,
    @ColumnInfo(name = "forks") val forks: Int,
    @ColumnInfo(name = "archive_url") val archiveUrl: String?,
    @ColumnInfo(name = "git_refs_url") val gitRefsUrl: String?,
    @ColumnInfo(name = "forks_url") val forksUrl: String?,
    @ColumnInfo(name = "statuses_url") val statusesUrl: String?,
    @ColumnInfo(name = "ssh_url") val sshUrl: String?,
    @ColumnInfo(name = "license_name") val licenseName: String?,
    @ColumnInfo(name = "full_name") val fullName: String?,
    @ColumnInfo(name = "size") val size: Int,
    @ColumnInfo(name = "languages_url") val languagesUrl: String?,
    @ColumnInfo(name = "html_url") val htmlUrl: String?,
    @ColumnInfo(name = "collaborators_url") val collaboratorsUrl: String?,
    @ColumnInfo(name = "clone_url") val cloneUrl: String?,
    @ColumnInfo(name = "name") val name: String,
    @ColumnInfo(name = "pulls_url") val pullsUrl: String?,
    @ColumnInfo(name = "default_branch") val defaultBranch: String?,
    @ColumnInfo(name = "hooks_url") val hooksUrl: String?,
    @ColumnInfo(name = "trees_url") val treesUrl: String?,
    @ColumnInfo(name = "tags_url") val tagsUrl: String?,
    @ColumnInfo(name = "private") val privateRepo: Boolean,
    @ColumnInfo(name = "contributors_url") val contributorsUrl: String?,
    @ColumnInfo(name = "has_downloads") val hasDownloads: Boolean,
    @ColumnInfo(name = "notifications_url") val notificationsUrl: String?,
    @ColumnInfo(name = "open_issues_count") val openIssuesCount: Int,
    @ColumnInfo(name = "description") val description: String?,
    @ColumnInfo(name = "created_at") val createdAt: String?,
    @ColumnInfo(name = "watchers") val watchers: Int,
    @ColumnInfo(name = "keys_url") val keysUrl: String?,
    @ColumnInfo(name = "deployments_url") val deploymentsUrl: String?,
    @ColumnInfo(name = "has_projects") val hasProjects: Boolean,
    @ColumnInfo(name = "archived") val archived: Boolean,
    @ColumnInfo(name = "has_wiki") val hasWiki: Boolean,
    @ColumnInfo(name = "updated_at") val updatedAt: String?,
    @ColumnInfo(name = "comments_url") val commentsUrl: String?,
    @ColumnInfo(name = "stargazers_url") val stargazersUrl: String?,
    @ColumnInfo(name = "git_url") val gitUrl: String?,
    @ColumnInfo(name = "has_pages") val hasPages: Boolean,
    @ColumnInfo(name = "owner_id") val ownerId: Long,
    @ColumnInfo(name = "commits_url") val commitsUrl: String?,
    @ColumnInfo(name = "compare_url") val compareUrl: String?,
    @ColumnInfo(name = "git_commits_url") val gitCommitsUrl: String?,
    @ColumnInfo(name = "blobs_url") val blobsUrl: String?,
    @ColumnInfo(name = "git_tags_url") val gitTagsUrl: String?,
    @ColumnInfo(name = "merges_url") val mergesUrl: String?,
    @ColumnInfo(name = "downloads_url") val downloadsUrl: String?,
    @ColumnInfo(name = "has_issues") val hasIssues: Boolean,
    @ColumnInfo(name = "url") val url: String,
    @ColumnInfo(name = "contents_url") val contentsUrl: String?,
    @ColumnInfo(name = "mirror_url") val mirrorUrl: String?,
    @ColumnInfo(name = "milestones_url") val milestonesUrl: String?,
    @ColumnInfo(name = "teams_url") val teamsUrl: String?,
    @ColumnInfo(name = "fork") val fork: Boolean,
    @ColumnInfo(name = "issues_url") val issuesUrl: String?,
    @ColumnInfo(name = "events_url") val eventsUrl: String?,
    @ColumnInfo(name = "issue_events_url") val issueEventsUrl: String?,
    @ColumnInfo(name = "assignees_url") val assigneesUrl: String?,
    @ColumnInfo(name = "open_issues") val openIssues: Int,
    @ColumnInfo(name = "watchers_count") val watchersCount: Int,
    @ColumnInfo(name = "node_id") val nodeId: String?,
    @ColumnInfo(name = "homepage") val homepage: String?,
    @ColumnInfo(name = "forks_count") val forksCount: Int,

    // to be consistent w/ changing backend order, we need to keep a data like this
    @ColumnInfo(name = "index_in_response") @PrimaryKey(autoGenerate = false) val indexInResponse: Int = -1
)